# Site settings
baseurl = "/making-metal-work/"
#baseurl = "/"
languageCode = "en-gb"
title = "Alec Mussell"
theme = "hugo-agency"
publishDir = "../docs"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Alec Mussell"
  description = "Making Metal Work"
  # email = "your@email.com"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  #disableFonts = false
  disableFonts = true

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation
  [params.navigation]
    brand = "Alec Mussell - Making Metal Work"
    # Optional logo as brand stored in img/
    #logo = "logo.svg"
    services = "Services"
    portfolio = "Portfolio"
    about = "About"
    reviews = "Reviews"
    contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Gates & Railings"
    #subtitle = "It's nice to meet you"
    buttonText = "Contact"


  # Services section
  [params.services]
    enable = true
    title = "Services"
    #subtitle = ""

    [[params.services.row]]

    [[params.services.row.list]]
      img = "gate.png"
      title = "Gates & Railings"
      description = "Hand made metal gates and railings made to measure with all installation included. Automated gate installation is also available"

    [[params.services.row.list]]
      img = "spanner.png"
      title = "Restoring existing metal work"
      description = "Removal of existing metal gates or railings for repair, restoration and repainting (powder coating)"

    [[params.services.row.list]]
      img = "blueprint.png"
      title = "Bespoke builds and designs"
      description = "From metal flowers to metal archways, we can work with you to make your metal work"

  # Portfolio section
  [params.portfolio]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Portfolio"
    #subtitle = ""

    [params.portfolio.modal]
      #client = "Client"
      #date = "Date"
      #category = "Category"
      buttonText = "Close project"


    # About section
  [params.about]
    enable = true
    title = "About"
    #subtitle = ""

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "phone.png"
      title = "Initial Contact"
      description = "We arrange a time and place to meet in person."

    [[params.about.events]]
      img = "blueprint.png"
      title = "Design"
      description = "Working alongside you to choose the right design and colours"

    [[params.about.events]]
      img = "welder.png"
      title = "Fabrication"
      description = "Your design is fabricated and made to measure, then sent to be powder coated in the colour of your choice. Galvanising available."

    [[params.about.events]]
      img = "gates.png"
      title = "Installation"
      description = "Gates and railings are then installed using any posts, fixtures and fittings as required"


#  # Comments section
  [params.reviews]
    enable = true
    # Possibility to center items
    #center = true
    title = "Reviews"
    #subtitle = ""
    #description = ""

    # Pictures are stored under 'static/img/reviews'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.reviews.members]]
      img = "comment.png"
      name = "Mr & Mrs Thompson"
      bio = """We struggled to find somebody who could create bespoke gates for our property.
Alec agreed to come to Hull and sat with us and designed just what we were looking for.
We are extremely happy with the results. The gates are of very high quality and have beautiful 
detail. We would highly recommend Alec to anyone.
"""

    [[params.reviews.members]]
      img = "comment.png"
      name = "Mr & Mrs Miller"
      bio = """Love our new gates. Bespoke gates made to our request. So please with finish.
Would highly recommend.
"""

    [[params.reviews.members]]
      img = "comment.png"
      name = "Mr & Mrs McCracken"
      bio = """Thanks Alec. The gates are great. You did a fantastic job. Thank you very much.
"""

#    [[params.reviews.members]]
#      img = "comment.webp"
#      name = "name"
#      bio = """multi-line
#comment"""


#  # Client section
#    [params.clients_list]
#      enable = true
#      # Possibility to center items
#      #center = true
#      # Optional client title specifying the involvement
#      #title = "Used and trusted by"
#
#      # All the clients' logos are stored under 'static/img/logos'.
#      # Replace them with your clients's logos.
#      # Suggestion: .svg in the size of 280px*80px looks good
#      [[params.clients]]
#        logo = "envato.jpg"
#        link = "#"
#
#      [[params.clients]]
#        logo = "designmodo.jpg"
#        link = "#"
#
#      [[params.clients]]
#        logo = "themeforest.jpg"
#        link = "#"
#
#      [[params.clients]]
#        logo = "creative-market.jpg"
#        link = "#"

  # Contact section
  [params.contact]
    name = "Alec Mussell"
    number = "07808 730692"
    email = "alecmussell@hotmail.com"
    facebook = "https://www.facebook.com/Makingmetalwork/"



    enable = true
    title = "Contact"

  # Footer section
  [params.footer]
    enable = false
    #copyright = "Published under the Apache License 2.0."

    #[[params.footer.social]]
    #  icon = "fa-twitter"
    #  link = "#"
    #  title = "Twitter"

    #[[params.footer.social]]
    #  icon = "fa-facebook"
    #  link = "#"
    #  title = "Facebook"

    #[[params.footer.social]]
    #  icon = "fa-linkedin"
    #  link = "#"
    #  title = "LinkedIn"

    #[[params.footer.quicklinks]]
    #  text = "Privacy Policy"
    #  link = "#"

    #[[params.footer.quicklinks]]
    #  text = "Terms of Use"
    #  link = "#"
